In [1]:
import os
os.getcwd()

'C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake'

In [2]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake')

In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import  DecisionTreeClassifier
import sklearn.ensemble as ensemble
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier

In [4]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter


#### chocolatecake , custardcake ,mouseecake, fruit cake , cupcake

#### total 31 files 70% of which is 22 is for training and 9 is for validation


### Chocolate - 3 , 4

In [39]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\chocolatecake\\chocolatehazelnut')

In [40]:
s1 = pd.read_csv('s1.csv')
s3 = pd.read_csv('s3.csv')
s4 = pd.read_csv('s4.csv')

In [41]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\chocolatecake\\oreochocolate')

In [42]:
s5 = pd.read_csv('s1.csv')
s6 = pd.read_csv('s2.csv')
s7 = pd.read_csv('s3.csv')
s8 = pd.read_csv('s4.csv')

In [43]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\custardcake\\caramelcustard')

In [44]:
s9 = pd.read_csv('s1.csv')
s10 = pd.read_csv('s2.csv')

In [45]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\moussecake\\ferrero rocher')

In [46]:
s11 = pd.read_csv('s1.csv')
s12 = pd.read_csv('s3.csv')
s13 = pd.read_csv('s4.csv')

In [47]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\moussecake\\orange')

In [48]:
s14 = pd.read_csv('s1.csv')
s15 = pd.read_csv('s2.csv')
s16 = pd.read_csv('s3.csv')
s17 = pd.read_csv('s4.csv')

In [49]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\moussecake\\yogurt')

In [50]:
s18 = pd.read_csv('s1.csv')
s19 = pd.read_csv('s2.csv')
s20 = pd.read_csv('s3.csv')
s21 = pd.read_csv('s4.csv')

In [51]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\fruitcake\\mixedfruit')

In [52]:
s22 = pd.read_csv('s1.csv')
s23 = pd.read_csv('s2.csv')
s24 = pd.read_csv('s3.csv')
s25 = pd.read_csv('s4.csv')

In [53]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cupcake\chocolate')

In [54]:
s26 = pd.read_csv('s1.csv')
s27 = pd.read_csv('s2.csv')
s28 = pd.read_csv('s3.csv')
s29 = pd.read_csv('s4.csv')

In [55]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cupcake\\vanilla')

In [56]:
s30 = pd.read_csv('s1.csv')
s31 = pd.read_csv('s2.csv')
s32 = pd.read_csv('s4.csv')

In [57]:
data = pd.concat([s1,s3,s4,s5,s6,s7,s8,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21,s22,s23,s24,s25],axis=0)

In [58]:
data2 = pd.concat([s9,s10,s26,s27,s28,s29,s30,s31,s32],axis=0)

In [59]:
data.shape

(11526, 10)

In [60]:
data = data.loc[data.nwords > 2, :]
data = data.loc[data.nnumbers <= 3, :]
data = data.loc[data.nwords <= 10, :]

In [61]:
data = data.drop(["Sentence"],axis=1)

In [62]:
X = data.drop("label",axis=1)
y = data.label

In [63]:
X.shape

(3990, 8)

## HT

## DT

In [65]:
from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn.model_selection import GridSearchCV
estimator =tree.DecisionTreeClassifier()

std_slc = StandardScaler()
pca = decomposition.PCA()
pipe = Pipeline(steps=[('std_slc', std_slc),
                           ('pca', pca),
                           ('dec_tree', estimator)])
n_components = list(range(1,X.shape[1]+1,1))
criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12]
parameters = dict(pca__n_components=n_components,
                      dec_tree__criterion=criterion,
                      dec_tree__max_depth=max_depth)

clf_GS = GridSearchCV(pipe, parameters)
clf_GS.fit(X, y)

GridSearchCV(estimator=Pipeline(steps=[('std_slc', StandardScaler()),
                                       ('pca', PCA()),
                                       ('dec_tree', DecisionTreeClassifier())]),
             param_grid={'dec_tree__criterion': ['gini', 'entropy'],
                         'dec_tree__max_depth': [2, 4, 6, 8, 10, 12],
                         'pca__n_components': [1, 2, 3, 4, 5, 6, 7, 8]})

In [66]:
clf_GS.best_estimator_.get_params()

{'memory': None,
 'steps': [('std_slc', StandardScaler()),
  ('pca', PCA(n_components=6)),
  ('dec_tree', DecisionTreeClassifier(max_depth=2))],
 'verbose': False,
 'std_slc': StandardScaler(),
 'pca': PCA(n_components=6),
 'dec_tree': DecisionTreeClassifier(max_depth=2),
 'std_slc__copy': True,
 'std_slc__with_mean': True,
 'std_slc__with_std': True,
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 6,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'dec_tree__ccp_alpha': 0.0,
 'dec_tree__class_weight': None,
 'dec_tree__criterion': 'gini',
 'dec_tree__max_depth': 2,
 'dec_tree__max_features': None,
 'dec_tree__max_leaf_nodes': None,
 'dec_tree__min_impurity_decrease': 0.0,
 'dec_tree__min_samples_leaf': 1,
 'dec_tree__min_samples_split': 2,
 'dec_tree__min_weight_fraction_leaf': 0.0,
 'dec_tree__random_state': None,
 'dec_tree__splitter': 'best'}

In [67]:
model_DT=DecisionTreeClassifier( max_depth=2, min_samples_leaf=1)
model_DT.fit(X,y)

DecisionTreeClassifier(max_depth=2)

## RF

In [68]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,max_features=0.5,oob_score=True)
randomForest.fit(X,y)

print(randomForest.base_estimator_)

print(randomForest.oob_score_)

DecisionTreeClassifier()
0.9817042606516291


In [69]:
from sklearn.model_selection import GridSearchCV
estimator = ensemble.RandomForestClassifier()



param_grid = { 
            "n_estimators"      : [10,20,30,40,50,60],
            "max_features"      : ["auto", "sqrt", "log2",0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
            "min_samples_split" : [2,4,8],
            }
grid = GridSearchCV(estimator, param_grid, n_jobs=-1, cv=5)   
grid.fit(X, y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_features': ['auto', 'sqrt', 'log2', 0.1, 0.2, 0.3,
                                          0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 20, 30, 40, 50, 60]})

In [70]:
grid.best_score_ , grid.best_params_

(0.9807017543859649,
 {'max_features': 0.5, 'min_samples_split': 4, 'n_estimators': 40})

In [71]:
randomForest = ensemble.RandomForestClassifier(n_estimators=40,min_samples_split = 4,max_features=0.5,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.5, min_samples_split=4, n_estimators=40,
                       oob_score=True)

## ADA

In [72]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [73]:
# define the grid of values to search
grid = dict()
grid['n_estimators'] = [10, 50, 100, 500]
grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]

from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# define the grid search procedure
grid_search = GridSearchCV(estimator=clf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy')

grid_result = grid_search.fit(X, y)
grid_result.best_score_, grid_result.best_params_


(0.9754385964912282, {'learning_rate': 1.0, 'n_estimators': 100})

In [74]:
clf_AD = AdaBoostClassifier(n_estimators=100, random_state=0,learning_rate= 1.0)
clf_AD.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

## SVM

In [75]:
clf1 = svm.SVC()
clf1.fit(X, y)

SVC()

In [76]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 
grid = GridSearchCV(clf1, param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(X, y)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.960 total time=   0.2s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.962 total time=   0.1s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.955 total time=   0.1s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.957 total time=   0.1s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.962 total time=   0.3s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.952 total time=   0.1s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.962 total time=   0.1s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.956 total time=   0.1s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.957 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.951 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.952 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.980 total time=   0.1s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.960 total time=   0.1s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.969 total time=   0.1s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.991 total time=   0.1s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.980 total time=   0.1s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.987 total time=   0.1s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.969 total time=   0.1s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.967 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.987 total time=   0.1s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.989 total time=   0.2s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.979 total time=   0.2s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.969 total time=   0.2s
[CV 4/5] END ....C=1000, gam

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [77]:
grid.best_params_,grid.best_estimator_

({'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}, SVC(C=10, gamma=0.1))

In [78]:
clf_SVM = svm.SVC(C=10,gamma=0.1)
clf_SVM.fit(X, y)

SVC(C=10, gamma=0.1)

## GBM

In [80]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X, y)

In [81]:
p_test = {'max_depth':[2,3,4,5,6,7] ,
           'learning_rate':[0.15,0.1,0.05,0.01,0.005,0.001], 'n_estimators':[100,250,500,750,1000,1250,1500,1750],
          }
tuning = GridSearchCV(estimator =clf2, param_grid = p_test, scoring='accuracy',n_jobs=4, cv=5)

In [82]:
tuning.fit(X,y)

GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(learning_rate=1.0,
                                                  max_depth=1, random_state=0),
             n_jobs=4,
             param_grid={'learning_rate': [0.15, 0.1, 0.05, 0.01, 0.005, 0.001],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 250, 500, 750, 1000, 1250, 1500,
                                          1750]},
             scoring='accuracy')

In [83]:
tuning.best_params_, tuning.best_score_

({'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 1000},
 0.9812030075187972)

In [84]:
clf_GBM = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.05,max_depth=3, random_state=0).fit(X, y)



In [85]:
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label


In [86]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1171  149]
 [  10   66]]
Prescision :  0.30697674418604654
Recall :  0.868421052631579
F1 score :  0.45360824742268047


In [87]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1238   82]
 [  12   64]]
Prescision :  0.4383561643835616
Recall :  0.8421052631578947
F1 score :  0.5765765765765766


In [88]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1293   27]
 [  16   60]]
Prescision :  0.6896551724137931
Recall :  0.7894736842105263
F1 score :  0.736196319018405


In [89]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1235   85]
 [  11   65]]
Prescision :  0.43333333333333335
Recall :  0.8552631578947368
F1 score :  0.575221238938053


In [90]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1229   91]
 [  11   65]]
Prescision :  0.4166666666666667
Recall :  0.8552631578947368
F1 score :  0.560344827586207


In [91]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT", " 0.306","  0.86", "  0.45"])
myTable.add_row(["RF", "0.43","0.842", " 0.576"])
myTable.add_row(["ADA", " 0.68","  0.789", " 0.736"])
myTable.add_row(["SVM", "0.43"," 0.855", "0.575"])
myTable.add_row(["GBM","0.41","0.855", "0.560"])

In [92]:
myTable

+-------+-----------+---------+----------+
| Model | Precision |  Recall | F1_score |
+-------+-----------+---------+----------+
|   DT  |    0.306  |    0.86 |    0.45  |
|   RF  |    0.43   |  0.842  |   0.576  |
|  ADA  |    0.68   |   0.789 |   0.736  |
|  SVM  |    0.43   |   0.855 |  0.575   |
|  GBM  |    0.41   |  0.855  |  0.560   |
+-------+-----------+---------+----------+

In [5]:
#### brownie , cocholatecake ,cupcake, fruit cake , pastry

#### total 42 files 70% of which is 29 is for training and 13 is for validation


In [ ]:
### Brownie - 3 , 3 , 4 

In [30]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\brownie\\oreo')

In [31]:
bo1 = pd.read_csv('s1.csv')
bo3 = pd.read_csv('s3.csv')
bo4 = pd.read_csv('s4.csv')


In [32]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\brownie\\snicker')

In [35]:
bs1 = pd.read_csv('s1.csv')
bs2 = pd.read_csv('s2.csv')
bs4 = pd.read_csv('s4.csv')


In [36]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\brownie\\swiss')

In [38]:
bsw1 = pd.read_csv('s1.csv')
bsw2 = pd.read_csv('s2.csv')
bsw3 = pd.read_csv('s3.csv')
bsw4 = pd.read_csv('s4.csv')

In [39]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\chocolatecake\\chocolatehazelnut')

In [40]:
s1 = pd.read_csv('s1.csv')
s3 = pd.read_csv('s3.csv')
s4 = pd.read_csv('s4.csv')

In [41]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\chocolatecake\\oreochocolate')

In [42]:
s5 = pd.read_csv('s1.csv')
s6 = pd.read_csv('s2.csv')
s7 = pd.read_csv('s3.csv')
s8 = pd.read_csv('s4.csv')

In [43]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cupcake\chocolate')

In [44]:
s26 = pd.read_csv('s1.csv')
s27 = pd.read_csv('s2.csv')
s28 = pd.read_csv('s3.csv')
s29 = pd.read_csv('s4.csv')

In [45]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cupcake\\vanilla')

In [46]:
s30 = pd.read_csv('s1.csv')
s31 = pd.read_csv('s2.csv')
s32 = pd.read_csv('s4.csv')

In [48]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\fruitcake\\mixedfruit')

In [49]:
s22 = pd.read_csv('s1.csv')
s23 = pd.read_csv('s2.csv')
s24 = pd.read_csv('s3.csv')
s25 = pd.read_csv('s4.csv')

In [50]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\almonddelight')

In [51]:
r1 = pd.read_csv('s1.csv')

In [53]:
data = pd.concat([bo1,bo3,bo4,bs1,bs2,bs4,bsw1,bsw2,bsw3,bsw4,s1,s3,s4,s5,s6,s7,s8,s26,s27,s28,s29,s30,s31,s32,s22,s23,s24,s25,r1],axis=0)

In [54]:
data.shape

(14998, 10)

In [55]:
data = data.loc[data.nwords > 2, :]
data = data.loc[data.nnumbers <= 3, :]
data = data.loc[data.nwords <= 10, :]
data = data.drop(["Sentence"],axis=1)
X = data.drop("label",axis=1)
y = data.label

In [56]:
from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn.model_selection import GridSearchCV
estimator =tree.DecisionTreeClassifier()

std_slc = StandardScaler()
pca = decomposition.PCA()
pipe = Pipeline(steps=[('std_slc', std_slc),
                           ('pca', pca),
                           ('dec_tree', estimator)])
n_components = list(range(1,X.shape[1]+1,1))
criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12]
parameters = dict(pca__n_components=n_components,
                      dec_tree__criterion=criterion,
                      dec_tree__max_depth=max_depth)

clf_GS = GridSearchCV(pipe, parameters)
clf_GS.fit(X, y)

GridSearchCV(estimator=Pipeline(steps=[('std_slc', StandardScaler()),
                                       ('pca', PCA()),
                                       ('dec_tree', DecisionTreeClassifier())]),
             param_grid={'dec_tree__criterion': ['gini', 'entropy'],
                         'dec_tree__max_depth': [2, 4, 6, 8, 10, 12],
                         'pca__n_components': [1, 2, 3, 4, 5, 6, 7, 8]})

In [57]:
clf_GS.best_estimator_.get_params()

{'memory': None,
 'steps': [('std_slc', StandardScaler()),
  ('pca', PCA(n_components=5)),
  ('dec_tree', DecisionTreeClassifier(max_depth=2))],
 'verbose': False,
 'std_slc': StandardScaler(),
 'pca': PCA(n_components=5),
 'dec_tree': DecisionTreeClassifier(max_depth=2),
 'std_slc__copy': True,
 'std_slc__with_mean': True,
 'std_slc__with_std': True,
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 5,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'dec_tree__ccp_alpha': 0.0,
 'dec_tree__class_weight': None,
 'dec_tree__criterion': 'gini',
 'dec_tree__max_depth': 2,
 'dec_tree__max_features': None,
 'dec_tree__max_leaf_nodes': None,
 'dec_tree__min_impurity_decrease': 0.0,
 'dec_tree__min_samples_leaf': 1,
 'dec_tree__min_samples_split': 2,
 'dec_tree__min_weight_fraction_leaf': 0.0,
 'dec_tree__random_state': None,
 'dec_tree__splitter': 'best'}

In [58]:
model_DT=DecisionTreeClassifier( max_depth=2, min_samples_leaf=1)
model_DT.fit(X,y)

DecisionTreeClassifier(max_depth=2)

In [59]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,max_features=0.5,oob_score=True)
randomForest.fit(X,y)

print(randomForest.base_estimator_)

print(randomForest.oob_score_)

DecisionTreeClassifier()
0.9819056785370549


In [60]:
from sklearn.model_selection import GridSearchCV
estimator = ensemble.RandomForestClassifier()



param_grid = { 
            "n_estimators"      : [10,20,30,40,50,60],
            "max_features"      : ["auto", "sqrt", "log2",0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
            "min_samples_split" : [2,4,8],
            }
grid = GridSearchCV(estimator, param_grid, n_jobs=-1, cv=5)   
grid.fit(X, y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_features': ['auto', 'sqrt', 'log2', 0.1, 0.2, 0.3,
                                          0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 20, 30, 40, 50, 60]})

In [61]:
grid.best_score_ , grid.best_params_

(0.9822906641000964,
 {'max_features': 0.1, 'min_samples_split': 8, 'n_estimators': 40})

In [62]:
randomForest = ensemble.RandomForestClassifier(n_estimators=40,min_samples_split = 8,max_features=0.1,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.1, min_samples_split=8, n_estimators=40,
                       oob_score=True)

In [63]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [64]:
# define the grid of values to search
grid = dict()
grid['n_estimators'] = [10, 50, 100, 500]
grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]

from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# define the grid search procedure
grid_search = GridSearchCV(estimator=clf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy')

grid_result = grid_search.fit(X, y)
grid_result.best_score_, grid_result.best_params_


(0.9834444938491183, {'learning_rate': 0.01, 'n_estimators': 500})

In [65]:
clf_AD = AdaBoostClassifier(n_estimators=500, random_state=0,learning_rate= 0.01)
clf_AD.fit(X, y)

AdaBoostClassifier(learning_rate=0.01, n_estimators=500, random_state=0)

In [66]:
clf1 = svm.SVC()
clf1.fit(X, y)

SVC()

In [67]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 
grid = GridSearchCV(clf1, param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(X, y)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.965 total time=   0.3s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.966 total time=   0.3s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.973 total time=   0.4s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.967 total time=   0.4s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.974 total time=   0.3s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.966 total time=   0.1s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.971 total time=   0.1s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.974 total time=   0.1s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.966 total time=   0.1s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.959 total time=   0.1s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.956 total time=   0.1s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.988 total time=   0.5s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.985 total time=   0.5s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.963 total time=   0.4s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.990 total time=   0.4s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.972 total time=   0.2s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.986 total time=   0.1s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.983 total time=   0.3s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.958 total time=   0.1s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.991 total time=   0.2s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.971 total time=   0.1s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.987 total time=   0.2s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.985 total time=   0.2s
[CV 4/5] END ....C=1000, gam

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [68]:
grid.best_params_,grid.best_estimator_

({'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}, SVC(C=10, gamma=0.001))

In [69]:
clf_SVM = svm.SVC(C=10,gamma=0.001)
clf_SVM.fit(X, y)

SVC(C=10, gamma=0.001)

In [96]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X, y)

In [97]:
p_test = {'max_depth':[2,3,4,5,6,7] ,
           'learning_rate':[0.15,0.1,0.05,0.01,0.005,0.001], 'n_estimators':[100,250,500,750,1000,1250,1500,1750],
          }
tuning = GridSearchCV(estimator =clf2, param_grid = p_test, scoring='accuracy',n_jobs=4, cv=5)

In [98]:
tuning.fit(X,y)

GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(learning_rate=1.0,
                                                  max_depth=1, random_state=0),
             n_jobs=4,
             param_grid={'learning_rate': [0.15, 0.1, 0.05, 0.01, 0.005, 0.001],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 250, 500, 750, 1000, 1250, 1500,
                                          1750]},
             scoring='accuracy')

In [99]:
tuning.best_params_, tuning.best_score_

({'learning_rate': 0.15, 'max_depth': 3, 'n_estimators': 1250},
 0.9824831568816169)

In [100]:
clf_GBM = GradientBoostingClassifier(n_estimators=1250, learning_rate=0.15,max_depth=3, random_state=0).fit(X, y)



In [75]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\almonddelight')

In [76]:
r2 = pd.read_csv('s2.csv')
r3 = pd.read_csv('s3.csv')
r4 = pd.read_csv('s4.csv')

In [77]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\deathbychocolate')

In [78]:
rr1 = pd.read_csv('s1.csv')
rr2 = pd.read_csv('s2.csv')
rr3 = pd.read_csv('s3.csv')
rr4 = pd.read_csv('s4.csv')

In [79]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\rainbow')

In [80]:
rrr1 = pd.read_csv('s1.csv')
rrr2 = pd.read_csv('s2.csv')
rrr3 = pd.read_csv('s3.csv')


In [81]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\rasmalai')

In [82]:

ras2 = pd.read_csv('s2.csv')
ras3 = pd.read_csv('s3.csv')
ras4 = pd.read_csv('s4.csv')

In [83]:
data8 = pd.concat([r2,r3,r4,rr1,rr2,rr3,rr4,rrr1,rrr2,rrr3,ras2,ras3,ras4],axis=0)

In [84]:
data8 = data8.loc[data8.nwords > 2, :]
data8 = data8.loc[data8.nnumbers <= 3, :]
data8 = data8.loc[data8.nwords <= 10, :]
data8 = data8.drop(["Sentence"],axis=1)
X_test = data8.drop("label",axis=1)
y_test = data8.label


In [85]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1603   10]
 [  32  107]]
Prescision :  0.9145299145299145
Recall :  0.7697841726618705
F1 score :  0.8359375


In [86]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1604    9]
 [  36  103]]
Prescision :  0.9196428571428571
Recall :  0.7410071942446043
F1 score :  0.8207171314741035


In [87]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1605    8]
 [  33  106]]
Prescision :  0.9298245614035088
Recall :  0.762589928057554
F1 score :  0.8379446640316206


In [88]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1603   10]
 [  32  107]]
Prescision :  0.9145299145299145
Recall :  0.7697841726618705
F1 score :  0.8359375


In [101]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1593   20]
 [  34  105]]
Prescision :  0.84
Recall :  0.7553956834532374
F1 score :  0.7954545454545454


In [ ]:
Prescision :  0.9145299145299145
Recall :  0.7697841726618705
F1 score :  0.8359375

In [94]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT", "0.91" , "0.76" , "0.83"])
myTable.add_row(["RF", "0.91","0.74", "0.82"])
myTable.add_row(["Ada",  "0.92"," 0.76", " 0.83"])
myTable.add_row(["SVM", "0.91"," 0.76", "0.83"])
myTable.add_row(["GBM","0.83","0.74", "0.79"])

In [95]:
myTable

+-------+-----------+-----------+--------+----------+
| Model | Site_Name | Precision | Recall | F1_score |
+-------+-----------+-----------+--------+----------+
|   DT  |   Pastry  |    0.91   |  0.76  |   0.83   |
|   RF  |   Pastry  |    0.91   |  0.74  |   0.82   |
|  Ada  |   Pastry  |    0.92   |  0.76  |   0.83   |
|  SVM  |   Pastry  |    0.91   |  0.76  |   0.83   |
|  GBM  |   Pastry  |    0.83   |  0.74  |   0.79   |
+-------+-----------+-----------+--------+----------+