In [16]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter


In [17]:
os.getcwd()

'C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\panneer'

In [18]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\panneer')

##### train the model on train set
    model = SVC()
    model.fit(X_train, y_train)

    # print prediction results
    predictions = model.predict(X_test)
    print(classification_report(y_test, predictions))


## focus only on the category cake 
for each dish extract the cleaned web content using the urls for that dish. Save these files as individual notebooks in a folder 
cake-subcategroy-file or each dish undder this category - under each dish data to be stored as separate text files.



##### 1 > train the model on data1 ,validate the model on the other data. 
    o/p table : 
    1c data 2c precisition 3c recall 4c no of 0's and no of 1's 5c f1 score
##### 2 >train the models on 4 randomly choosen data collated together
      use CV to choose appropriate hyperparameters
      Test the model
      1>on the remaining 4 data individually
      2> on a single test data created by appending the 4 test data
##### 3>Test the model on a dataset on gobi and chicken manchurian
       
       
#### The model sequence
     1>DT
     2>RF
     3>Adaboost
     4>SVM
     5>GBM

In [19]:
data1 = pd.read_csv('site1.csv')

In [20]:
data1

Sentence  newline_after  \
0                       skip to primary navigation              1   
1                             skip to main content              1   
2                          skip to primary sidebar              0   
3    yummy tummy https //wwwyummytummyaarthicom/wp              1   
4                 content/uploads/2017/05/tummypng              2   
..                                             ...            ...   
496                                   recipe index              2   
497                                     newsletter              2   
498                                        sign up              0   
499                         for emails and updates              2   
500                                 stay connected              2   

     newline_before  nwords  numbers  nnumbers  nnouns  nverbs  nunits   label  
0                 0       4        0         0       2       0        0      0  
1                 1       4        0         0       2       0        0      0  
2                 1       4        0         0       2       0        0      0  
3                 0       4        0         0       4       0        0      0  
4                 1       1        1         6       1       0        0      0  
..              ...     ...      ...       ...     ...     ...      ...    ...  
496               1       2        0         0       2       0        0      0  
497               2       1        0         0       1       0        0      0  
498               2       2        0         0       1       0        0      0  
499               0       4        0         0       2       0        0      0  
500               2       2        0         0       1       1        0      0  

[501 rows x 10 columns]

In [21]:
data1 = data1.drop(["Sentence"],axis=1)

In [22]:
data1 = data1.loc[data1.nwords > 2, :]
data1 = data1.loc[data1.nnumbers <= 3, :]
data1 = data1.loc[data1.nwords <= 10, :]

In [23]:
import sklearn.ensemble as ensemble

In [24]:
X = data1.drop("label",axis=1)

In [25]:
y = data1.label

#### 1 > train the model on data1 ,validate the model on the other data.¶

### Decision Tree

In [26]:
from sklearn.tree import  DecisionTreeClassifier


In [27]:
model=DecisionTreeClassifier( max_depth=3, min_samples_leaf=5)
model.fit(X,y)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5)

In [28]:
data2 = pd.read_csv('site2.csv')


In [29]:
data2.describe()

newline_after  newline_before      nwords     numbers    nnumbers  \
count     721.000000      721.000000  721.000000  721.000000  721.000000   
mean        1.208044        1.205270    7.359223    0.380028    3.524272   
std         0.715691        0.716492    6.014099    0.485730    7.560664   
min         0.000000        0.000000    1.000000    0.000000    0.000000   
25%         1.000000        1.000000    3.000000    0.000000    0.000000   
50%         1.000000        1.000000    5.000000    0.000000    0.000000   
75%         2.000000        2.000000   12.000000    1.000000    2.000000   
max         4.000000        4.000000   30.000000    1.000000   27.000000   

           nnouns      nverbs     nunits        label  
count  721.000000  721.000000  721.000000  721.000000  
mean     2.837725    0.919556    0.113731    0.059639  
std      1.900297    1.175759    0.317705    0.236982  
min      0.000000    0.000000    0.000000    0.000000  
25%      1.000000    0.000000    0.000000    0.000000  
50%      3.000000    1.000000    0.000000    0.000000  
75%      4.000000    2.000000    0.000000    0.000000  
max     12.000000    7.000000    1.000000    1.000000

In [31]:
data2['label'].isnull().sum()

0

In [35]:
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]

In [36]:
#len(data2.Sentence[pred == 1])                     ###predicted

In [37]:
#len(data2.Sentence[data2.label == 1])             ## actual

In [38]:
data2 = data2.drop(["Sentence"],axis=1)

In [39]:
X_test = data2.drop("label",axis=1)
y_test = data2.label

In [42]:
print(Counter(y_test))

Counter({0: 221, 1: 37})


In [43]:
pred = model.predict(X_test)

In [44]:
pd.crosstab(y_test,pred)

col_0    0   1
label         
0      215   6
1        7  30

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[215,   6],
       [  7,  30]], dtype=int64)

In [46]:
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score


In [47]:
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))


Prescision :  0.8333333333333334
Recall :  0.8108108108108109


In [48]:
# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


F1 score :  0.8219178082191781


### Random Forest

In [49]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,max_features=0.5,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.5, n_estimators=50, oob_score=True)

In [50]:
randomForest.base_estimator_

DecisionTreeClassifier()

In [51]:
pred1 = randomForest.predict(X_test)

In [52]:
randomForest.score(X,y)

0.9939024390243902

In [53]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred1)

array([[211,  10],
       [  6,  31]], dtype=int64)

In [54]:
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred1))
print("Recall : " , recall_score(y_test, pred1))


Prescision :  0.7560975609756098
Recall :  0.8378378378378378


In [55]:
# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred1))


F1 score :  0.7948717948717948


### AdaBoost

In [56]:
from sklearn.ensemble import AdaBoostClassifier

In [57]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [58]:
clf.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [59]:
pred2 = clf.predict(X_test)

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred2)

array([[211,  10],
       [  9,  28]], dtype=int64)

In [61]:
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred2))
print("Recall : " , recall_score(y_test, pred2))


Prescision :  0.7368421052631579
Recall :  0.7567567567567568


In [62]:
# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred2))


F1 score :  0.7466666666666667


### SVM

In [63]:
from sklearn import svm
clf1 = svm.SVC()

In [64]:
clf1.fit(X, y)

SVC()

In [65]:
pred3 = clf1.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred3)

array([[218,   3],
       [ 15,  22]], dtype=int64)

In [67]:
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred3))
print("Recall : " , recall_score(y_test, pred3))


Prescision :  0.88
Recall :  0.5945945945945946


In [68]:
# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred3))


F1 score :  0.7096774193548386


### GBM

In [71]:
from sklearn.ensemble import GradientBoostingClassifier

In [72]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X, y)

In [73]:
pred4 = clf2.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred4)

array([[207,  14],
       [  6,  31]], dtype=int64)

In [75]:
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred4))
print("Recall : " , recall_score(y_test, pred4))


Prescision :  0.6888888888888889
Recall :  0.8378378378378378


In [76]:
# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred4))


F1 score :  0.7560975609756098


In [201]:
os.chdir('d:\\spark_install\\lib\\site-packages')

In [78]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score","No of 0's","No of 1's","Predicted 0's","Predicted1's"])
myTable.add_row(["Decision Tree","Site2", "0.834","0.8109", "0.821","221","37","215","30"])
myTable.add_row(["Random Forest","Site2", "0.775","0.837", "0.805","221","37","211","31"])
myTable.add_row(["Adaboost","Site2", "0.736","0.756", "0.746","221","37","211","28"])

myTable.add_row(["SVM","Site2", "0.88","0.594", "0.709","221","37","218","22"])
myTable.add_row(["GBM","Site2", "0.689","0.837", "0.756","221","37","207","31"])

In [79]:
myTable

+---------------+-----------+-----------+--------+----------+-----------+-----------+---------------+--------------+
|     Model     | Site_Name | Precision | Recall | F1_score | No of 0's | No of 1's | Predicted 0's | Predicted1's |
+---------------+-----------+-----------+--------+----------+-----------+-----------+---------------+--------------+
| Decision Tree |   Site2   |   0.834   | 0.8109 |  0.821   |    221    |     37    |      215      |      30      |
| Random Forest |   Site2   |   0.775   | 0.837  |  0.805   |    221    |     37    |      211      |      31      |
|    Adaboost   |   Site2   |   0.736   | 0.756  |  0.746   |    221    |     37    |      211      |      28      |
|      SVM      |   Site2   |    0.88   | 0.594  |  0.709   |    221    |     37    |      218      |      22      |
|      GBM      |   Site2   |   0.689   | 0.837  |  0.756   |    221    |     37    |      207      |      31      |
+---------------+-----------+-----------+--------+----------+-----------+-----------+---------------+--------------+

### 2 >train the models on 4 randomly choosen data collated together use CV to choose appropriate hyperparameters

In [79]:
## site 2,5,7,4

In [80]:
os.getcwd()

'd:\\spark_install\\lib\\site-packages'

In [309]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\panneer')

In [310]:
site2 = pd.read_csv('site2.csv')
site5 = pd.read_csv('site5.csv')
site7 = pd.read_csv('site7.csv')
site4 = pd.read_csv('site4.csv')

In [311]:
data_com = pd.concat([site2,site5,site7,site4],axis=0)

In [312]:
data_com.shape

(1932, 10)

In [313]:
data_com = data_com.loc[data_com.nwords > 2, :]
data_com = data_com.loc[data_com.nnumbers <= 3, :]
data_com = data_com.loc[data_com.nwords <= 10, :]

In [314]:
data_com = data_com.drop(["Sentence"],axis=1)

In [315]:
X = data_com.drop("label",axis=1)
y = data_com.label

In [88]:
model=DecisionTreeClassifier( max_depth=3, min_samples_leaf=5)
model.fit(X,y)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5)

In [89]:
site1 = pd.read_csv('site1.csv')
site3 = pd.read_csv('site3.csv')
site6 = pd.read_csv('site6.csv')
site8 = pd.read_csv('site8.csv')

In [91]:
data_c = pd.concat([site1,site3,site6,site8],axis=0)

data_com = data_com.loc[data_com.nwords > 2, :]
data_com = data_com.loc[data_com.nnumbers <= 3, :]
data_com = data_com.loc[data_com.nwords <= 10, :]
data_com = data_com.drop(["Sentence"],axis=1)
X_test = data_c.drop("label",axis=1)
y_test = data_c.label
pred2 = clf.predict(X_test)


In [92]:
X_test = data_c.drop("label",axis=1)
y_test = data_c.label

## Hyperparameter

In [93]:
from sklearn import tree

In [94]:
from sklearn.model_selection import GridSearchCV

In [95]:
estimator =tree.DecisionTreeClassifier()

In [96]:
    from sklearn import decomposition, datasets
    from sklearn import tree
    from sklearn.pipeline import Pipeline
    from sklearn.model_selection import GridSearchCV
    from sklearn.preprocessing import StandardScaler

In [97]:
 std_slc = StandardScaler()

In [98]:
  pca = decomposition.PCA()

In [99]:
 pipe = Pipeline(steps=[('std_slc', std_slc),
                           ('pca', pca),
                           ('dec_tree', estimator)])

In [100]:
  n_components = list(range(1,X.shape[1]+1,1))

In [101]:
criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12]

In [102]:
parameters = dict(pca__n_components=n_components,
                      dec_tree__criterion=criterion,
                      dec_tree__max_depth=max_depth)

In [103]:
clf_GS = GridSearchCV(pipe, parameters)
clf_GS.fit(X, y)

GridSearchCV(estimator=Pipeline(steps=[('std_slc', StandardScaler()),
                                       ('pca', PCA()),
                                       ('dec_tree', DecisionTreeClassifier())]),
             param_grid={'dec_tree__criterion': ['gini', 'entropy'],
                         'dec_tree__max_depth': [2, 4, 6, 8, 10, 12],
                         'pca__n_components': [1, 2, 3, 4, 5, 6, 7, 8]})

In [104]:
clf_GS.best_estimator_.get_params()

{'memory': None,
 'steps': [('std_slc', StandardScaler()),
  ('pca', PCA(n_components=8)),
  ('dec_tree', DecisionTreeClassifier(max_depth=4))],
 'verbose': False,
 'std_slc': StandardScaler(),
 'pca': PCA(n_components=8),
 'dec_tree': DecisionTreeClassifier(max_depth=4),
 'std_slc__copy': True,
 'std_slc__with_mean': True,
 'std_slc__with_std': True,
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 8,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'dec_tree__ccp_alpha': 0.0,
 'dec_tree__class_weight': None,
 'dec_tree__criterion': 'gini',
 'dec_tree__max_depth': 4,
 'dec_tree__max_features': None,
 'dec_tree__max_leaf_nodes': None,
 'dec_tree__min_impurity_decrease': 0.0,
 'dec_tree__min_samples_leaf': 1,
 'dec_tree__min_samples_split': 2,
 'dec_tree__min_weight_fraction_leaf': 0.0,
 'dec_tree__random_state': None,
 'dec_tree__splitter': 'best'}

In [105]:
model_DT=DecisionTreeClassifier( max_depth=6, min_samples_leaf=1)
model_DT.fit(X,y)

DecisionTreeClassifier(max_depth=6)

In [202]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["Decision Tree","Site1", "1","0.687", " 0.814"])
myTable.add_row(["Decision Tree","Site3", "0.875","0.823", "0.848"])
myTable.add_row(["Decision Tree","Site6", "0","0", "0"])
myTable.add_row(["Decision Tree","Site8", "1","0.476", "0.645"])
myTable.add_row(["Decision Tree","combined", "0.954","0.666", "0.785"])

In [203]:
myTable

+---------------+-----------+-----------+--------+----------+
|     Model     | Site_Name | Precision | Recall | F1_score |
+---------------+-----------+-----------+--------+----------+
| Decision Tree |   Site1   |     1     | 0.687  |   0.814  |
| Decision Tree |   Site3   |   0.875   | 0.823  |  0.848   |
| Decision Tree |   Site6   |     0     |   0    |    0     |
| Decision Tree |   Site8   |     1     | 0.476  |  0.645   |
| Decision Tree |  combined |   0.954   | 0.666  |  0.785   |
+---------------+-----------+-----------+--------+----------+

In [106]:
### TEST 1,3,6,8

In [107]:
data2 = pd.read_csv('site1.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[132   0]
 [ 10  22]]
Prescision :  1.0
Recall :  0.6875
F1 score :  0.8148148148148148


In [108]:
data2 = pd.read_csv('site3.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[217   2]
 [  3  14]]
Prescision :  0.875
Recall :  0.8235294117647058
F1 score :  0.8484848484848485


In [109]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[47  0]
 [ 2  0]]
Prescision :  0.0
Recall :  0.0
F1 score :  0.0


D:\Spark_install\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [110]:
os.chdir('d:\\spark_install\\lib\\site-packages')

In [111]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter


### CLass imbalance issue 

In [114]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\panneer')

In [288]:
data = pd.read_csv('site6.csv')
data = data.drop(["Sentence"],axis=1)

In [289]:
X = data.drop("label",axis=1)
y = data.label

In [290]:
print(Counter(y))

Counter({0: 144, 1: 9})


In [291]:
###site 6

# instantiating the random over sampler 
ros = RandomOverSampler()
# resampling X, y
X_ros, y_ros = ros.fit_resample(X, y)
# new class distribution 
print(Counter(y_ros))

##

Counter({0: 144, 1: 144})


In [277]:
##site 8

# instantiating the random over sampler 
ros = RandomOverSampler()
# resampling X, y
X_ros1, y_ros1 = ros.fit_resample(X, y)
# new class distribution 
print(Counter(y_ros))


Counter({0: 144, 1: 144})


In [292]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = model_DT.predict(X_ros)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros, pred))
print("Recall : " , recall_score(y_ros, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros, pred))


[[144   0]
 [144   0]]
Prescision :  0.0
Recall :  0.0
F1 score :  0.0


D:\Spark_install\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [293]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = randomForest.predict(X_ros)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros, pred))
print("Recall : " , recall_score(y_ros, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros, pred))


[[142   2]
 [  0 144]]
Prescision :  0.9863013698630136
Recall :  1.0
F1 score :  0.993103448275862


In [294]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = clf_AD.predict(X_ros)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros, pred))
print("Recall : " , recall_score(y_ros, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros, pred))


[[143   1]
 [ 28 116]]
Prescision :  0.9914529914529915
Recall :  0.8055555555555556
F1 score :  0.888888888888889


In [295]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = clf_SVM.predict(X_ros)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros, pred))
print("Recall : " , recall_score(y_ros, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros, pred))


[[144   0]
 [110  34]]
Prescision :  1.0
Recall :  0.2361111111111111
F1 score :  0.38202247191011235


In [328]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = clf_GBM.predict(X_ros)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros, pred))
print("Recall : " , recall_score(y_ros, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros, pred))


[[143   1]
 [ 34 110]]
Prescision :  0.990990990990991
Recall :  0.7638888888888888
F1 score :  0.8627450980392156


In [282]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[67  0]
 [ 6  6]]
Prescision :  1.0
Recall :  0.5
F1 score :  0.6666666666666666


In [283]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = model_DT.predict(X_ros1)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros1, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros1, pred))
print("Recall : " , recall_score(y_ros1, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros1, pred))


[[346   0]
 [161 185]]
Prescision :  1.0
Recall :  0.5346820809248555
F1 score :  0.696798493408663


In [284]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = randomForest.predict(X_ros1)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros1, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros1, pred))
print("Recall : " , recall_score(y_ros1, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros1, pred))


[[346   0]
 [ 86 260]]
Prescision :  1.0
Recall :  0.7514450867052023
F1 score :  0.858085808580858


In [285]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = clf_AD.predict(X_ros1)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros1, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros1, pred))
print("Recall : " , recall_score(y_ros1, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros1, pred))


[[345   1]
 [161 185]]
Prescision :  0.9946236559139785
Recall :  0.5346820809248555
F1 score :  0.6954887218045114


In [286]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = clf_SVM.predict(X_ros1)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros1, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros1, pred))
print("Recall : " , recall_score(y_ros1, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros1, pred))


[[346   0]
 [161 185]]
Prescision :  1.0
Recall :  0.5346820809248555
F1 score :  0.696798493408663


In [329]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)

pred = clf_GBM.predict(X_ros1)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_ros1, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_ros1, pred))
print("Recall : " , recall_score(y_ros1, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_ros1, pred))


[[346   0]
 [ 86 260]]
Prescision :  1.0
Recall :  0.7514450867052023
F1 score :  0.858085808580858


In [123]:
data_c = pd.concat([site1,site3,site6,site8],axis=0)
data_c = data_c.loc[data_c.nwords > 2, :]
data_c = data_c.loc[data_c.nnumbers <= 3, :]
data_c = data_c.loc[data_c.nwords <= 10, :]
data_c = data_c.drop(["Sentence"],axis=1)
X_test = data_c.drop("label",axis=1)
y_test = data_c.label
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[463   2]
 [ 21  42]]
Prescision :  0.9545454545454546
Recall :  0.6666666666666666
F1 score :  0.7850467289719627


## 2

In [222]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,max_features=0.5,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.5, n_estimators=50, oob_score=True)

In [223]:
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.5, n_estimators=50, oob_score=True)

In [224]:
randomForest.base_estimator_

DecisionTreeClassifier()

In [225]:
randomForest.oob_score_

0.9741496598639455

In [226]:
from sklearn.model_selection import GridSearchCV

In [227]:
estimator = ensemble.RandomForestClassifier()

In [228]:
param_grid = { 
            "n_estimators"      : [10,20,30,40,50,60],
            "max_features"      : ["auto", "sqrt", "log2",0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
            "min_samples_split" : [2,4,8],
            }

In [229]:
grid = GridSearchCV(estimator, param_grid, n_jobs=-1, cv=5)   

In [230]:
grid.fit(X, y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_features': ['auto', 'sqrt', 'log2', 0.1, 0.2, 0.3,
                                          0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 20, 30, 40, 50, 60]})

In [233]:
grid.best_score_ , grid.best_params_

(0.9755102040816327,
 {'max_features': 0.3, 'min_samples_split': 2, 'n_estimators': 60})

In [234]:
randomForest = ensemble.RandomForestClassifier(n_estimators=60,min_samples_split = 2,max_features=0.3,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.3, n_estimators=60, oob_score=True)

In [242]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["RandomForest","Site1", "0.966"," 0.906", " 0.935"])
myTable.add_row(["RandomForest","Site3", "0.736","0.823", "0.777"])
myTable.add_row(["RandomForest","Site6", "0.986"," 1.0", " 0.993"])
myTable.add_row(["RandomForest","Site8", "1"," 0.765", "0.867"])
myTable.add_row(["RandomForest","combined", "0.9","0.857", "0.878"])

In [243]:
myTable 

+--------------+-----------+-----------+--------+----------+
|    Model     | Site_Name | Precision | Recall | F1_score |
+--------------+-----------+-----------+--------+----------+
| RandomForest |   Site1   |   0.966   |  0.906 |   0.935  |
| RandomForest |   Site3   |   0.736   | 0.823  |  0.777   |
| RandomForest |   Site6   |   0.986   |   1.0  |   0.993  |
| RandomForest |   Site8   |     1     |  0.765 |  0.867   |
| RandomForest |  combined |    0.9    | 0.857  |  0.878   |
+--------------+-----------+-----------+--------+----------+

In [ ]:

[[131   1]
 [  3  29]]
Prescision :  0.9666666666666667
Recall :  0.90625
F1 score :  0.9354838709677419
    
[[214   5]
 [  3  14]]
Prescision :  0.7368421052631579
Recall :  0.8235294117647058
F1 score :  0.7777777777777778    
    
    
[[142   2]
 [  0 144]]
Prescision :  0.9863013698630136
Recall :  1.0
F1 score :  0.993103448275862    
    
[[346   0]
 [ 81 265]]
Prescision :  1.0
Recall :  0.7658959537572254
F1 score :  0.867430441898527
    
    
[[459   6]
 [  9  54]]
Prescision :  0.9
Recall :  0.8571428571428571
F1 score :  0.8780487804878048

In [235]:
data2 = pd.read_csv('site1.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[131   1]
 [  3  29]]
Prescision :  0.9666666666666667
Recall :  0.90625
F1 score :  0.9354838709677419


In [236]:
data2 = pd.read_csv('site3.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[214   5]
 [  3  14]]
Prescision :  0.7368421052631579
Recall :  0.8235294117647058
F1 score :  0.7777777777777778


In [237]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[47  0]
 [ 0  2]]
Prescision :  1.0
Recall :  1.0
F1 score :  1.0


In [238]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[67  0]
 [ 3  9]]
Prescision :  1.0
Recall :  0.75
F1 score :  0.8571428571428571


In [239]:
data_c = pd.concat([site1,site3,site6,site8],axis=0)
data_c = data_c.loc[data_c.nwords > 2, :]
data_c = data_c.loc[data_c.nnumbers <= 3, :]
data_c = data_c.loc[data_c.nwords <= 10, :]
data_c = data_c.drop(["Sentence"],axis=1)
X_test = data_c.drop("label",axis=1)
y_test = data_c.label
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[459   6]
 [  9  54]]
Prescision :  0.9
Recall :  0.8571428571428571
F1 score :  0.8780487804878048


## 3

In [244]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [245]:
# define the grid of values to search
grid = dict()
grid['n_estimators'] = [10, 50, 100, 500]
grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]

In [246]:
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [247]:
# define the grid search procedure
grid_search = GridSearchCV(estimator=clf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy')

In [248]:
grid_result = grid_search.fit(X, y)
grid_result.best_score_, grid_result.best_params_

(0.9665000617055413, {'learning_rate': 0.01, 'n_estimators': 500})

In [249]:
clf_AD = AdaBoostClassifier(n_estimators=500, random_state=0,learning_rate= 0.01)
clf_AD.fit(X, y)

AdaBoostClassifier(learning_rate=0.01, n_estimators=500, random_state=0)

In [256]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["AdaBoost","Site1", "1"," 0.718", " 0.836"])
myTable.add_row(["AdaBoost","Site3", "0.833","0.882", "0.857"])
myTable.add_row(["AdaBoost","Site6", "0.99"," 0.756", " 0.858"])
myTable.add_row(["AdaBoost","Site8", "0.993"," 0.476", "0.644"])
myTable.add_row(["AdaBoost","combined", "0.938","0.730", "0.821"])

In [257]:
myTable

+----------+-----------+-----------+--------+----------+
|  Model   | Site_Name | Precision | Recall | F1_score |
+----------+-----------+-----------+--------+----------+
| AdaBoost |   Site1   |     1     |  0.718 |   0.836  |
| AdaBoost |   Site3   |   0.833   | 0.882  |  0.857   |
| AdaBoost |   Site6   |    0.99   |  0.756 |   0.858  |
| AdaBoost |   Site8   |   0.993   |  0.476 |  0.644   |
| AdaBoost |  combined |   0.938   | 0.730  |  0.821   |
+----------+-----------+-----------+--------+----------+

In [ ]:
[[132   0]
 [  9  23]]
Prescision :  1.0
Recall :  0.71875
F1 score :  0.8363636363636363
  

[[216   3]
 [  2  15]]
Prescision :  0.8333333333333334
Recall :  0.8823529411764706
F1 score :  0.8571428571428571
    

    
    [[143   1]
 [ 35 109]]
Prescision :  0.990909090909091
Recall :  0.7569444444444444
F1 score :  0.858267716535433

    
[[345   1]
 [181 165]]
Prescision :  0.9939759036144579
Recall :  0.476878612716763
F1 score :  0.64453125
    

[[462   3]
 [ 17  46]]
Prescision :  0.9387755102040817
Recall :  0.7301587301587301
F1 score :  0.8214285714285714


In [250]:
data2 = pd.read_csv('site1.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[132   0]
 [  9  23]]
Prescision :  1.0
Recall :  0.71875
F1 score :  0.8363636363636363


In [251]:
data2 = pd.read_csv('site3.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[216   3]
 [  2  15]]
Prescision :  0.8333333333333334
Recall :  0.8823529411764706
F1 score :  0.8571428571428571


In [148]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[47  0]
 [ 0  2]]
Prescision :  1.0
Recall :  1.0
F1 score :  1.0


In [149]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[67  0]
 [10  2]]
Prescision :  1.0
Recall :  0.16666666666666666
F1 score :  0.2857142857142857


In [258]:
data_c = pd.concat([site1,site3,site6,site8],axis=0)
data_c = data_c.loc[data_c.nwords > 2, :]
data_c = data_c.loc[data_c.nnumbers <= 3, :]
data_c = data_c.loc[data_c.nwords <= 10, :]
data_c = data_c.drop(["Sentence"],axis=1)
X_test = data_c.drop("label",axis=1)
y_test = data_c.label
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[462   3]
 [ 17  46]]
Prescision :  0.9387755102040817
Recall :  0.7301587301587301
F1 score :  0.8214285714285714


## 4

In [259]:
clf1 = svm.SVC()
clf1.fit(X, y)

SVC()

In [260]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 
grid = GridSearchCV(clf1, param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(X, y)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.891 total time=   0.1s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.891 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.891 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.884 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.884 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.891 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.891 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.891 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.884 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.884 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.891 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.925 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.939 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.932 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.959 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.959 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.973 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.966 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.973 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.973 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.952 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.973 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.952 total time=   0.0s
[CV 3/5] END ...C=1000, gamm

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [261]:
grid.best_params_,grid.best_estimator_

({'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}, SVC(C=100, gamma=0.01))

In [262]:
clf_SVM = svm.SVC(C=100,gamma=0.01)
clf_SVM.fit(X, y)

SVC(C=100, gamma=0.01)

In [ ]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["SVM","Site1", "1"," 0.718", " 0.836"])
myTable.add_row(["SVM","Site3", "0.833","0.882", "0.857"])
myTable.add_row(["SVM","Site6", "0.99"," 0.756", " 0.858"])
myTable.add_row(["SVM","Site8", "0.993"," 0.476", "0.644"])
myTable.add_row(["SVM","combined", "0.938","0.730", "0.821"])

In [ ]:
[[132   0]
 [  9  23]]
Prescision :  1.0
Recall :  0.71875
F1 score :  0.8363636363636363
    
[[213   6]
 [  3  14]]
Prescision :  0.7
Recall :  0.8235294117647058
F1 score :  0.7567567567567567
   


   

[[346   0]
 [181 165]]
Prescision :  1.0
Recall :  0.476878612716763
F1 score :  0.6457925636007827

    
[[459   6]
 [ 18  45]]
Prescision :  0.8823529411764706
Recall :  0.7142857142857143
F1 score :  0.7894736842105262

In [297]:
data2 = pd.read_csv('site1.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[132   0]
 [  9  23]]
Prescision :  1.0
Recall :  0.71875
F1 score :  0.8363636363636363


In [298]:
data2 = pd.read_csv('site3.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[213   6]
 [  3  14]]
Prescision :  0.7
Recall :  0.8235294117647058
F1 score :  0.7567567567567567


In [301]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[47  0]
 [ 0  2]]
Prescision :  1.0
Recall :  1.0
F1 score :  1.0


In [271]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[67  0]
 [ 6  6]]
Prescision :  1.0
Recall :  0.5
F1 score :  0.6666666666666666


In [299]:
data_c = pd.concat([site1,site3,site6,site8],axis=0)
data_c = data_c.loc[data_c.nwords > 2, :]
data_c = data_c.loc[data_c.nnumbers <= 3, :]
data_c = data_c.loc[data_c.nwords <= 10, :]
data_c = data_c.drop(["Sentence"],axis=1)
X_test = data_c.drop("label",axis=1)
y_test = data_c.label
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[459   6]
 [ 18  45]]
Prescision :  0.8823529411764706
Recall :  0.7142857142857143
F1 score :  0.7894736842105262


## 5

In [316]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X, y)

In [317]:
p_test = {'max_depth':[2,3,4,5,6,7] ,
           'learning_rate':[0.15,0.1,0.05,0.01,0.005,0.001], 'n_estimators':[100,250,500,750,1000,1250,1500,1750],
          }
tuning = GridSearchCV(estimator =clf2, param_grid = p_test, scoring='accuracy',n_jobs=4, cv=5)

In [318]:
tuning.fit(X,y)

GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(learning_rate=1.0,
                                                  max_depth=1, random_state=0),
             n_jobs=4,
             param_grid={'learning_rate': [0.15, 0.1, 0.05, 0.01, 0.005, 0.001],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 250, 500, 750, 1000, 1250, 1500,
                                          1750]},
             scoring='accuracy')

In [319]:
tuning.best_params_, tuning.best_score_

({'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 1750},
 0.9768707482993196)

In [320]:
clf_GBM = GradientBoostingClassifier(n_estimators=1750, learning_rate=0.01,max_depth=3, random_state=0).fit(X, y)



In [323]:
data2 = pd.read_csv('site1.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[131   1]
 [  3  29]]
Prescision :  0.9666666666666667
Recall :  0.90625
F1 score :  0.9354838709677419


In [324]:
data2 = pd.read_csv('site3.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[217   2]
 [  4  13]]
Prescision :  0.8666666666666667
Recall :  0.7647058823529411
F1 score :  0.8125


In [325]:
data2 = pd.read_csv('site6.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[47  0]
 [ 2  0]]
Prescision :  0.0
Recall :  0.0
F1 score :  0.0


D:\Spark_install\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [326]:
data2 = pd.read_csv('site8.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[67  0]
 [ 3  9]]
Prescision :  1.0
Recall :  0.75
F1 score :  0.8571428571428571


In [327]:
data_c = pd.concat([site1,site3,site6,site8],axis=0)
data_c = data_c.loc[data_c.nwords > 2, :]
data_c = data_c.loc[data_c.nnumbers <= 3, :]
data_c = data_c.loc[data_c.nwords <= 10, :]
data_c = data_c.drop(["Sentence"],axis=1)
X_test = data_c.drop("label",axis=1)
y_test = data_c.label
pred =clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[462   3]
 [ 12  51]]
Prescision :  0.9444444444444444
Recall :  0.8095238095238095
F1 score :  0.8717948717948718


## 3>Test the model on a dataset on gobi and chicken manchurian

https://www.indianhealthyrecipes.com/chicken-manchurian-recipe/
https://hebbarskitchen.com/dry-gobi-manchurian-recipe/

In [171]:
os.getcwd()

'C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\panneer'

## gobi machurian

In [330]:
data2 = pd.read_csv('gobi.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label



In [331]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[104   0]
 [  5  15]]
Prescision :  1.0
Recall :  0.75
F1 score :  0.8571428571428571


In [332]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[104   0]
 [  3  17]]
Prescision :  1.0
Recall :  0.85
F1 score :  0.9189189189189189


In [333]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[104   0]
 [  5  15]]
Prescision :  1.0
Recall :  0.75
F1 score :  0.8571428571428571


In [334]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[104   0]
 [  5  15]]
Prescision :  1.0
Recall :  0.75
F1 score :  0.8571428571428571


In [335]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[104   0]
 [  3  17]]
Prescision :  1.0
Recall :  0.85
F1 score :  0.9189189189189189


### chicken machurian

In [344]:
data2 = pd.read_csv('chicken.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label


In [345]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[227   1]
 [  4  16]]
Prescision :  0.9411764705882353
Recall :  0.8
F1 score :  0.8648648648648648


In [346]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[226   2]
 [  2  18]]
Prescision :  0.9
Recall :  0.9
F1 score :  0.9


In [347]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[226   2]
 [  2  18]]
Prescision :  0.9
Recall :  0.9
F1 score :  0.9


In [348]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[226   2]
 [  2  18]]
Prescision :  0.9
Recall :  0.9
F1 score :  0.9


In [349]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[227   1]
 [  3  17]]
Prescision :  0.9444444444444444
Recall :  0.85
F1 score :  0.8947368421052632
