In [8]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.ensemble as ensemble

In [2]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter


In [3]:
os.getcwd()

'C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)'

In [10]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\panneer')

In [11]:
data1 = pd.read_csv('site1.csv')

In [12]:
data1 = data1.drop(["Sentence"],axis=1)

In [40]:
data1 = data1.loc[data1.nwords > 2, :]
data1 = data1.loc[data1.nnumbers <= 3, :]
data1 = data1.loc[data1.nwords <= 10, :]

In [14]:
X = data1.drop("label",axis=1)
y = data1.label

In [ ]:
# 1

In [17]:
from sklearn.tree import  DecisionTreeClassifier


In [15]:
    from sklearn import tree
    from sklearn.model_selection import GridSearchCV
    estimator =tree.DecisionTreeClassifier()
    from sklearn import decomposition, datasets
    from sklearn import tree
    from sklearn.pipeline import Pipeline
    from sklearn.model_selection import GridSearchCV
    from sklearn.preprocessing import StandardScaler
    std_slc = StandardScaler()
    pca = decomposition.PCA()
    pipe = Pipeline(steps=[('std_slc', std_slc),
                           ('pca', pca),
                           ('dec_tree', estimator)])
    n_components = list(range(1,X.shape[1]+1,1))
    criterion = ['gini', 'entropy']
    max_depth = [2,4,6,8,10,12]
    parameters = dict(pca__n_components=n_components,
                      dec_tree__criterion=criterion,
                      dec_tree__max_depth=max_depth)
    clf_GS = GridSearchCV(pipe, parameters)
    clf_GS.fit(X, y)
    clf_GS.best_estimator_.get_params()

{'memory': None,
 'steps': [('std_slc', StandardScaler()),
  ('pca', PCA(n_components=7)),
  ('dec_tree', DecisionTreeClassifier(criterion='entropy', max_depth=4))],
 'verbose': False,
 'std_slc': StandardScaler(),
 'pca': PCA(n_components=7),
 'dec_tree': DecisionTreeClassifier(criterion='entropy', max_depth=4),
 'std_slc__copy': True,
 'std_slc__with_mean': True,
 'std_slc__with_std': True,
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 7,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'dec_tree__ccp_alpha': 0.0,
 'dec_tree__class_weight': None,
 'dec_tree__criterion': 'entropy',
 'dec_tree__max_depth': 4,
 'dec_tree__max_features': None,
 'dec_tree__max_leaf_nodes': None,
 'dec_tree__min_impurity_decrease': 0.0,
 'dec_tree__min_samples_leaf': 1,
 'dec_tree__min_samples_split': 2,
 'dec_tree__min_weight_fraction_leaf': 0.0,
 'dec_tree__random_state': None,
 'dec_tree__splitter': 'best'}

In [18]:
model_DT=DecisionTreeClassifier( max_depth=4, min_samples_leaf=1)
model_DT.fit(X,y)

DecisionTreeClassifier(max_depth=4)

In [19]:
data2 = pd.read_csv('site2.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[212   9]
 [  6  31]]
Prescision :  0.775
Recall :  0.8378378378378378
F1 score :  0.8051948051948051


In [ ]:
# 2

In [20]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,max_features=0.5,oob_score=True)
randomForest.fit(X,y)
randomForest.base_estimator_
randomForest.oob_score_
from sklearn.model_selection import GridSearchCV
estimator = ensemble.RandomForestClassifier()
param_grid = { 
            "n_estimators"      : [10,20,30,40,50,60],
            "max_features"      : ["auto", "sqrt", "log2",0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
            "min_samples_split" : [2,4,8],
            }
grid = GridSearchCV(estimator, param_grid, n_jobs=-1, cv=5)   
grid.fit(X, y)
grid.best_score_ , grid.best_params_

(0.9816287878787879,
 {'max_features': 'auto', 'min_samples_split': 4, 'n_estimators': 50})

In [21]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,min_samples_split = 4,max_features=0.3,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.3, min_samples_split=4, n_estimators=50,
                       oob_score=True)

In [22]:
data2 = pd.read_csv('site2.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))
# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[214   7]
 [  6  31]]
Prescision :  0.8157894736842105
Recall :  0.8378378378378378
F1 score :  0.8266666666666665


In [ ]:
# 3

In [24]:
from sklearn.ensemble import AdaBoostClassifier

In [25]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)
# define the grid of values to search
grid = dict()
grid['n_estimators'] = [10, 50, 100, 500]
grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# define the grid search procedure
grid_search = GridSearchCV(estimator=clf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy')
grid_result = grid_search.fit(X, y)
grid_result.best_score_, grid_result.best_params_

(0.9696078431372548, {'learning_rate': 0.1, 'n_estimators': 500})

In [26]:
clf_AD = AdaBoostClassifier(n_estimators=500, random_state=0,learning_rate= 0.1)
clf_AD.fit(X, y)

AdaBoostClassifier(learning_rate=0.1, n_estimators=500, random_state=0)

In [27]:
data2 = pd.read_csv('site2.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[208  13]
 [  6  31]]
Prescision :  0.7045454545454546
Recall :  0.8378378378378378
F1 score :  0.7654320987654323


In [ ]:
# 4

In [29]:
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
clf1 = svm.SVC()
clf1.fit(X, y)
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 
grid = GridSearchCV(clf1, param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(X, y)



Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.818 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.818 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.788 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.788 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.812 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.818 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.818 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.788 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.788 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.812 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.818 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.938 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.879 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.939 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.939 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.939 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.938 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.970 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.939 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.939 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.939 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.938 total time=   0.0s


({'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}, SVC(C=10, gamma=0.1))

In [31]:
grid.best_params_,grid.best_estimator_

({'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}, SVC(C=10, gamma=0.1))

In [32]:
clf_SVM = svm.SVC(C=10,gamma=0.1)
clf_SVM.fit(X, y)

SVC(C=10, gamma=0.1)

In [33]:
data2 = pd.read_csv('site2.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[212   9]
 [ 11  26]]
Prescision :  0.7428571428571429
Recall :  0.7027027027027027
F1 score :  0.7222222222222223


In [ ]:
# 5

In [34]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X, y)
p_test = {'max_depth':[2,3,4,5,6,7] ,
           'learning_rate':[0.15,0.1,0.05,0.01,0.005,0.001], 'n_estimators':[100,250,500,750,1000,1250,1500,1750],
          }
tuning = GridSearchCV(estimator =clf2, param_grid = p_test, scoring='accuracy',n_jobs=4, cv=5)
tuning.fit(X,y)

GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(learning_rate=1.0,
                                                  max_depth=1, random_state=0),
             n_jobs=4,
             param_grid={'learning_rate': [0.15, 0.1, 0.05, 0.01, 0.005, 0.001],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 250, 500, 750, 1000, 1250, 1500,
                                          1750]},
             scoring='accuracy')

In [35]:
tuning.best_params_, tuning.best_score_

({'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100},
 0.9816287878787879)

In [36]:
clf_GBM = GradientBoostingClassifier(n_estimators=100, learning_rate=0.05,max_depth=3, random_state=0).fit(X, y)



In [37]:
data2 = pd.read_csv('site2.csv')
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))


[[213   8]
 [  6  31]]
Prescision :  0.7948717948717948
Recall :  0.8378378378378378
F1 score :  0.8157894736842105


In [ ]:
os.chdir('d:\\spark_install\\lib\\site-packages')

In [38]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score","No of 0's","No of 1's","Predicted 0's","Predicted1's"])
myTable.add_row(["Decision Tree","Site2", " 0.775"," 0.837", "0.805","221","37","212","31"])
myTable.add_row(["Random Forest","Site2", "0.815","0.837", "0.826","221","37","214","31"])

myTable.add_row(["Adaboost","Site2", "0.704","0.837", "0.765","221","37","208","31"])

myTable.add_row(["SVM","Site2", "0.742","0.702", "0.722","221","37","212","26"])

myTable.add_row(["GBM","Site2", "0.794","0.837", " 0.815","221","37","213","31"])

In [39]:
myTable

+---------------+-----------+-----------+--------+----------+-----------+-----------+---------------+--------------+
|     Model     | Site_Name | Precision | Recall | F1_score | No of 0's | No of 1's | Predicted 0's | Predicted1's |
+---------------+-----------+-----------+--------+----------+-----------+-----------+---------------+--------------+
| Decision Tree |   Site2   |    0.775  |  0.837 |  0.805   |    221    |     37    |      212      |      31      |
| Random Forest |   Site2   |   0.815   | 0.837  |  0.826   |    221    |     37    |      214      |      31      |
|    Adaboost   |   Site2   |   0.704   | 0.837  |  0.765   |    221    |     37    |      208      |      31      |
|      SVM      |   Site2   |   0.742   | 0.702  |  0.722   |    221    |     37    |      212      |      26      |
|      GBM      |   Site2   |   0.794   | 0.837  |   0.815  |    221    |     37    |      213      |      31      |
+---------------+-----------+-----------+--------+----------+-----------+-----------+---------------+--------------+