In [1]:
import os
os.getcwd()

'C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake'

In [2]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake')

In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import  DecisionTreeClassifier
import sklearn.ensemble as ensemble
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier

In [5]:
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter


#### brownie , cheesecake ,teacake, fruit pastry , cupcake

#### total 48 files 70% of which is 34 is for training and 14 is for validation


### Brownie - 3 , 3 , 4 

In [6]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\brownie\\oreo')

In [7]:
bo1 = pd.read_csv('s1.csv')
bo3 = pd.read_csv('s3.csv')
bo4 = pd.read_csv('s4.csv')


In [8]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\brownie\\snicker')

In [9]:
bs1 = pd.read_csv('s1.csv')
bs2 = pd.read_csv('s2.csv')
bs4 = pd.read_csv('s4.csv')


In [10]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\brownie\\swiss')

In [11]:
bsw1 = pd.read_csv('s1.csv')
bsw2 = pd.read_csv('s2.csv')
bsw3 = pd.read_csv('s3.csv')
bsw4 = pd.read_csv('s4.csv')

### Cheesecake 3,3,4

In [12]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cheesecake\\blueberry')

In [13]:
cb1 = pd.read_csv('s1.csv')
cb3 = pd.read_csv('s3.csv')
cb4 = pd.read_csv('s4.csv')


In [14]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cheesecake\\newyork')

In [15]:
cy1 = pd.read_csv('s1.csv')
cy2 = pd.read_csv('s2.csv')
cy3 = pd.read_csv('s3.csv')


In [16]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cheesecake\\redvelvet')

In [17]:
cv1 = pd.read_csv('s1.csv')
cv2 = pd.read_csv('s2.csv')
cv3 = pd.read_csv('s3.csv')
cv4 = pd.read_csv('s4.csv')

### Teacake 3,3,3,4

In [18]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\teacake\\banana')

In [19]:
tb1 = pd.read_csv('s1.csv')
tb3 = pd.read_csv('s3.csv')
tb4 = pd.read_csv('s4.csv')


In [20]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\teacake\\cottagecheese')

In [21]:
tcc2 = pd.read_csv('s2.csv')
tcc3 = pd.read_csv('s3.csv')
tcc4 = pd.read_csv('s4.csv')


In [22]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\teacake\\irish')

In [23]:
ti1 = pd.read_csv('s1.csv')
ti3 = pd.read_csv('s3.csv')
ti4 = pd.read_csv('s4.csv')


In [24]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\teacake\\pina colada')

In [25]:
tp1 = pd.read_csv('s1.csv')
tp2 = pd.read_csv('s2.csv')
tp3 = pd.read_csv('s3.csv')
tp4 = pd.read_csv('s4.csv')

### Fruit pastry 1 

In [26]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\fruitpastry\\blueberry')

In [27]:
fpb1 = pd.read_csv('s1.csv')

### training data total 34 

In [28]:
data = pd.concat([bo1,bo3,bo4,bs1,bs2,bs4,bsw1,bsw2,bsw3,bsw4,cb1,cb3,cb4,cy1,cy2,cy3,cv1,cv2,cv3,cv4,tb1,tb3,tb4,tcc2,tcc3,tcc4,ti1,ti3,ti4,tp1,tp2,tp3,tp4,fpb1],axis=0)

In [29]:
data.shape

(22548, 10)

In [78]:
type(data)

pandas.core.frame.DataFrame

In [30]:
data.columns

Index(['Sentence', 'newline_after', 'newline_before', 'nwords', 'numbers',
       'nnumbers', 'nnouns', 'nverbs', 'nunits ', 'label'],
      dtype='object')

In [31]:
#data.to_csv('file1.csv')

In [32]:
data = data.loc[data.nwords > 2, :]
data = data.loc[data.nnumbers <= 3, :]
data = data.loc[data.nwords <= 10, :]

In [33]:
data = data.drop(["Sentence"],axis=1)

In [34]:
X = data.drop("label",axis=1)
y = data.label

In [35]:
X.shape

(7900, 8)

In [36]:
y.shape

(7900,)

## Hyperparameter tuning

### 1. Decision Tree

In [45]:
from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

In [46]:
from sklearn import tree
from sklearn.model_selection import GridSearchCV
estimator =tree.DecisionTreeClassifier()
   

In [47]:
std_slc = StandardScaler()
pca = decomposition.PCA()
pipe = Pipeline(steps=[('std_slc', std_slc),
                           ('pca', pca),
                           ('dec_tree', estimator)])
n_components = list(range(1,X.shape[1]+1,1))
criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12]
parameters = dict(pca__n_components=n_components,
                      dec_tree__criterion=criterion,
                      dec_tree__max_depth=max_depth)

In [48]:
clf_GS = GridSearchCV(pipe, parameters)
clf_GS.fit(X, y)

GridSearchCV(estimator=Pipeline(steps=[('std_slc', StandardScaler()),
                                       ('pca', PCA()),
                                       ('dec_tree', DecisionTreeClassifier())]),
             param_grid={'dec_tree__criterion': ['gini', 'entropy'],
                         'dec_tree__max_depth': [2, 4, 6, 8, 10, 12],
                         'pca__n_components': [1, 2, 3, 4, 5, 6, 7, 8]})

In [49]:
clf_GS.best_estimator_.get_params()

{'memory': None,
 'steps': [('std_slc', StandardScaler()),
  ('pca', PCA(n_components=6)),
  ('dec_tree', DecisionTreeClassifier(max_depth=10))],
 'verbose': False,
 'std_slc': StandardScaler(),
 'pca': PCA(n_components=6),
 'dec_tree': DecisionTreeClassifier(max_depth=10),
 'std_slc__copy': True,
 'std_slc__with_mean': True,
 'std_slc__with_std': True,
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 6,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'dec_tree__ccp_alpha': 0.0,
 'dec_tree__class_weight': None,
 'dec_tree__criterion': 'gini',
 'dec_tree__max_depth': 10,
 'dec_tree__max_features': None,
 'dec_tree__max_leaf_nodes': None,
 'dec_tree__min_impurity_decrease': 0.0,
 'dec_tree__min_samples_leaf': 1,
 'dec_tree__min_samples_split': 2,
 'dec_tree__min_weight_fraction_leaf': 0.0,
 'dec_tree__random_state': None,
 'dec_tree__splitter': 'best'}

In [50]:
model_DT=DecisionTreeClassifier( max_depth=10, min_samples_leaf=1)
model_DT.fit(X,y)

DecisionTreeClassifier(max_depth=10)

### 2.Random Forest

In [51]:
randomForest = ensemble.RandomForestClassifier(n_estimators=50,max_features=0.5,oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features=0.5, n_estimators=50, oob_score=True)

In [52]:
randomForest.base_estimator_

DecisionTreeClassifier()

In [53]:
randomForest.oob_score_

0.9821518987341772

In [54]:
from sklearn.model_selection import GridSearchCV
estimator = ensemble.RandomForestClassifier()

In [55]:
param_grid = { 
            "n_estimators"      : [10,20,30,40,50,60],
            "max_features"      : ["auto", "sqrt", "log2",0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
            "min_samples_split" : [2,4,8],
            }
grid = GridSearchCV(estimator, param_grid, n_jobs=-1, cv=5)   
grid.fit(X, y)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_features': ['auto', 'sqrt', 'log2', 0.1, 0.2, 0.3,
                                          0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 20, 30, 40, 50, 60]})

In [56]:
grid.best_score_ , grid.best_params_

(0.9845569620253165,
 {'max_features': 'sqrt', 'min_samples_split': 8, 'n_estimators': 40})

In [57]:
randomForest = ensemble.RandomForestClassifier(n_estimators=40,min_samples_split = 8,max_features='sqrt',oob_score=True)
randomForest.fit(X,y)

RandomForestClassifier(max_features='sqrt', min_samples_split=8,
                       n_estimators=40, oob_score=True)

### 3.AdaBoost

In [58]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [59]:
# define the grid of values to search
grid = dict()
grid['n_estimators'] = [10, 50, 100, 500]
grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]

from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# define the grid search procedure
grid_search = GridSearchCV(estimator=clf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy')

grid_result = grid_search.fit(X, y)
grid_result.best_score_, grid_result.best_params_


(0.9813924050632913, {'learning_rate': 1.0, 'n_estimators': 10})

In [60]:
clf_AD = AdaBoostClassifier(n_estimators=10, random_state=0,learning_rate= 1.0)
clf_AD.fit(X, y)

AdaBoostClassifier(n_estimators=10, random_state=0)

### 4.SVM

In [61]:
clf1 = svm.SVC()
clf1.fit(X, y)

SVC()

In [62]:
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
 
grid = GridSearchCV(clf1, param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(X, y)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.971 total time=   0.6s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.970 total time=   0.9s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.973 total time=   1.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.976 total time=   0.6s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.967 total time=   0.5s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.982 total time=   0.3s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.983 total time=   0.3s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.978 total time=   0.2s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.987 total time=   0.2s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.973 total time=   0.2s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.961 total time=   0.3s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.984 total time=   1.1s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.978 total time=   0.8s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.991 total time=   0.9s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.980 total time=   0.8s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.968 total time=   0.6s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.985 total time=   0.7s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.975 total time=   0.4s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.994 total time=   0.4s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.976 total time=   0.3s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.987 total time=   0.6s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.986 total time=   0.6s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.981 total time=   0.8s
[CV 4/5] END ....C=1000, gam

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [63]:
grid.best_params_,grid.best_estimator_

({'C': 1000, 'gamma': 0.01, 'kernel': 'rbf'}, SVC(C=1000, gamma=0.01))

In [64]:
clf_SVM = svm.SVC(C=1000,gamma=0.01)
clf_SVM.fit(X, y)

SVC(C=1000, gamma=0.01)

### 5.GBM

In [65]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X, y)

In [66]:
p_test = {'max_depth':[2,3,4,5,6,7] ,
           'learning_rate':[0.15,0.1,0.05,0.01,0.005,0.001], 'n_estimators':[100,250,500,750,1000,1250,1500,1750],
          }
tuning = GridSearchCV(estimator =clf2, param_grid = p_test, scoring='accuracy',n_jobs=4, cv=5)

In [67]:
tuning.fit(X,y)

GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(learning_rate=1.0,
                                                  max_depth=1, random_state=0),
             n_jobs=4,
             param_grid={'learning_rate': [0.15, 0.1, 0.05, 0.01, 0.005, 0.001],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'n_estimators': [100, 250, 500, 750, 1000, 1250, 1500,
                                          1750]},
             scoring='accuracy')

In [68]:
tuning.best_params_, tuning.best_score_

({'learning_rate': 0.01, 'max_depth': 2, 'n_estimators': 1250},
 0.9837974683544305)

In [69]:
clf_GBM = GradientBoostingClassifier(n_estimators=1250, learning_rate=0.01,max_depth=2, random_state=0).fit(X, y)



### Test data

In [ ]:
### Fruit Pastry 7

In [70]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\fruitpastry\\blueberry')

In [71]:
fpb2 = pd.read_csv('s2.csv')
fpb3 = pd.read_csv('s3.csv')
fpb4 = pd.read_csv('s4.csv')

In [72]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\fruitpastry\\raspberry')

In [73]:
fpr1 = pd.read_csv('s1.csv')
fpr2 = pd.read_csv('s2.csv')
fpr3 = pd.read_csv('s3.csv')
fpr4 = pd.read_csv('s4.csv')

In [74]:
### Cup cake 7

In [75]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cupcake\\chocolate')

In [76]:
cc1 = pd.read_csv('s1.csv')
cc2 = pd.read_csv('s2.csv')
cc3 = pd.read_csv('s3.csv')
cc4 = pd.read_csv('s4.csv')

In [77]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\cupcake\\vanilla')

In [78]:
cva1 = pd.read_csv('s1.csv')
cva2 = pd.read_csv('s2.csv')
cva4 = pd.read_csv('s4.csv')

In [79]:
data2 = pd.concat([fpb2,fpb3,fpb4,fpr1,fpr2,fpr3,fpr4,cc1,cc2,cc3,cc4,cva1,cva2,cva4],axis=0)

In [80]:
data2 = data2.loc[data2.nwords > 2, :]
data2 = data2.loc[data2.nnumbers <= 3, :]
data2 = data2.loc[data2.nwords <= 10, :]
data2 = data2.drop(["Sentence"],axis=1)
X_test = data2.drop("label",axis=1)
y_test = data2.label


In [81]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[2141   79]
 [  29   79]]
Prescision :  0.5
Recall :  0.7314814814814815
F1 score :  0.5939849624060151


In [82]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[2180   40]
 [  25   83]]
Prescision :  0.6747967479674797
Recall :  0.7685185185185185
F1 score :  0.7186147186147186


In [83]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[2167   53]
 [  31   77]]
Prescision :  0.5923076923076923
Recall :  0.7129629629629629
F1 score :  0.6470588235294117


In [84]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[2165   55]
 [  28   80]]
Prescision :  0.5925925925925926
Recall :  0.7407407407407407
F1 score :  0.6584362139917694


In [85]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[2167   53]
 [  26   82]]
Prescision :  0.6074074074074074
Recall :  0.7592592592592593
F1 score :  0.6748971193415638


In [ ]:
Prescision :  0.5925925925925926
Recall :  0.7407407407407407
F1 score :  0.6584362139917694

In [86]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT", "0.5"," 0.731", " 0.593"])
myTable.add_row(["RF", "0.67","0.768", "0.718"])
myTable.add_row(["ADA", "0.59"," 0.712", " 0.647"])
myTable.add_row(["SVM", "0.59"," 0.740", "0.658"])
myTable.add_row(["GBM","0.60","0.759", "0.674"])

In [87]:
myTable

+-------+-----------+--------+----------+
| Model | Precision | Recall | F1_score |
+-------+-----------+--------+----------+
|   DT  |    0.5    |  0.731 |   0.593  |
|   RF  |    0.67   | 0.768  |  0.718   |
|  ADA  |    0.59   |  0.712 |   0.647  |
|  SVM  |    0.59   |  0.740 |  0.658   |
|  GBM  |    0.60   | 0.759  |  0.674   |
+-------+-----------+--------+----------+

## other folders

### chocolatecake

In [91]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\chocolatecake\\chocolatehazelnut')

In [92]:
ch1 = pd.read_csv('s1.csv')
ch3 = pd.read_csv('s3.csv')
ch4 = pd.read_csv('s4.csv')

In [93]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\chocolatecake\\oreochocolate')

In [94]:
cho1 = pd.read_csv('s1.csv')
cho2 = pd.read_csv('s2.csv')
cho3 = pd.read_csv('s3.csv')
cho4 = pd.read_csv('s4.csv')

In [97]:
data3 = pd.concat([ch1,ch3,ch4,cho1,cho2,cho3,cho4],axis=0)

In [99]:
data3 = data3.loc[data3.nwords > 2, :]
data3 = data3.loc[data3.nnumbers <= 3, :]
data3 = data3.loc[data3.nwords <= 10, :]
data3 = data3.drop(["Sentence"],axis=1)
X_test = data3.drop("label",axis=1)
y_test = data3.label


In [100]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1221    6]
 [  12   51]]
Prescision :  0.8947368421052632
Recall :  0.8095238095238095
F1 score :  0.8500000000000001


In [101]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1224    3]
 [  11   52]]
Prescision :  0.9454545454545454
Recall :  0.8253968253968254
F1 score :  0.8813559322033897


In [102]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1222    5]
 [  14   49]]
Prescision :  0.9074074074074074
Recall :  0.7777777777777778
F1 score :  0.8376068376068377


In [103]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1224    3]
 [  11   52]]
Prescision :  0.9454545454545454
Recall :  0.8253968253968254
F1 score :  0.8813559322033897


In [104]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1223    4]
 [  10   53]]
Prescision :  0.9298245614035088
Recall :  0.8412698412698413
F1 score :  0.8833333333333334


In [115]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT","Chocolatecake", "0.89" , "0.809" , "0.850"])
myTable.add_row(["RF","Chocolatecake", "0.94","0.825", "0.881"])
myTable.add_row(["Ada","Chocolatecake",  "0.90"," 0.77", " 0.837"])
myTable.add_row(["SVM","Chocolatecake", "0.945"," 0.825", "0.881"])
myTable.add_row(["GBM","Chocolatecake","0.92","0.841", "0.883"])

In [116]:
myTable

+-------+---------------+-----------+--------+----------+
| Model |   Site_Name   | Precision | Recall | F1_score |
+-------+---------------+-----------+--------+----------+
|   DT  | Chocolatecake |    0.89   | 0.809  |  0.850   |
|   RF  | Chocolatecake |    0.94   | 0.825  |  0.881   |
|  Ada  | Chocolatecake |    0.90   |  0.77  |   0.837  |
|  SVM  | Chocolatecake |   0.945   |  0.825 |  0.881   |
|  GBM  | Chocolatecake |    0.92   | 0.841  |  0.883   |
+-------+---------------+-----------+--------+----------+

### creamcake

In [118]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\creamcake\\rainbow')

In [119]:
cra1 = pd.read_csv('s1.csv')
cra4 = pd.read_csv('s4.csv')

In [123]:
data4 = pd.concat([cra1,cra4],axis=0)

In [124]:
data4 = data4.loc[data4.nwords > 2, :]
data4 = data4.loc[data4.nnumbers <= 3, :]
data4 = data4.loc[data4.nwords <= 10, :]
data4 = data4.drop(["Sentence"],axis=1)
X_test = data4.drop("label",axis=1)
y_test = data4.label


In [125]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[228   1]
 [  6  19]]
Prescision :  0.95
Recall :  0.76
F1 score :  0.8444444444444444


In [126]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[229   0]
 [  7  18]]
Prescision :  1.0
Recall :  0.72
F1 score :  0.8372093023255813


In [127]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[229   0]
 [  8  17]]
Prescision :  1.0
Recall :  0.68
F1 score :  0.8095238095238095


In [128]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[229   0]
 [  8  17]]
Prescision :  1.0
Recall :  0.68
F1 score :  0.8095238095238095


In [129]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[229   0]
 [  7  18]]
Prescision :  1.0
Recall :  0.72
F1 score :  0.8372093023255813


In [130]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT","Creamcake", "0.95" , "0.76" , "0.844"])
myTable.add_row(["RF","Creamcake", "1","0.72", "0.837"])
myTable.add_row(["Ada","Creamcake",  "1"," 0.68", " 0.809"])
myTable.add_row(["SVM","Creamcake", "1"," 0.68", "0.809"])
myTable.add_row(["GBM","Creamcake","1","0.72", "0.837"])

In [131]:
myTable

+-------+-----------+-----------+--------+----------+
| Model | Site_Name | Precision | Recall | F1_score |
+-------+-----------+-----------+--------+----------+
|   DT  | Creamcake |    0.95   |  0.76  |  0.844   |
|   RF  | Creamcake |     1     |  0.72  |  0.837   |
|  Ada  | Creamcake |     1     |  0.68  |   0.809  |
|  SVM  | Creamcake |     1     |  0.68  |  0.809   |
|  GBM  | Creamcake |     1     |  0.72  |  0.837   |
+-------+-----------+-----------+--------+----------+

### custard cake 

In [148]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\custardcake\\caramelcustard')

In [149]:
cracus1 = pd.read_csv('s1.csv')
cracus2 = pd.read_csv('s2.csv')

In [150]:
data5 = pd.concat([cracus1,cracus2],axis=0)

In [151]:
data5 = data5.loc[data5.nwords > 2, :]
data5 = data5.loc[data5.nnumbers <= 3, :]
data5 = data5.loc[data5.nwords <= 10, :]
data5 = data5.drop(["Sentence"],axis=1)
X_test = data5.drop("label",axis=1)
y_test = data5.label


In [152]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[398   0]
 [  5   4]]
Prescision :  1.0
Recall :  0.4444444444444444
F1 score :  0.6153846153846153


In [142]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[397   1]
 [  2   7]]
Prescision :  0.875
Recall :  0.7777777777777778
F1 score :  0.823529411764706


In [143]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[397   1]
 [  3   6]]
Prescision :  0.8571428571428571
Recall :  0.6666666666666666
F1 score :  0.75


In [144]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[397   1]
 [  2   7]]
Prescision :  0.875
Recall :  0.7777777777777778
F1 score :  0.823529411764706


In [145]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[397   1]
 [  2   7]]
Prescision :  0.875
Recall :  0.7777777777777778
F1 score :  0.823529411764706


In [172]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT","Custardcake", "1" , "0.44" , "0.615"])
myTable.add_row(["RF","Custardcake", "0.875","0.77", "0.823"])
myTable.add_row(["Ada","Custardcake",  "0.85"," 0.66", " 0.75"])
myTable.add_row(["SVM","Custardcake", "0.875"," 0.77", "0.823"])
myTable.add_row(["GBM","Custardcake","0.875","0.77", "0.823"])

In [ ]:
Prescision :  1.0
Recall :  0.4444444444444444
F1 score :  0.6153846153846153

In [173]:
myTable

+-------+-------------+-----------+--------+----------+
| Model |  Site_Name  | Precision | Recall | F1_score |
+-------+-------------+-----------+--------+----------+
|   DT  | Custardcake |     1     |  0.44  |  0.615   |
|   RF  | Custardcake |   0.875   |  0.77  |  0.823   |
|  Ada  | Custardcake |    0.85   |  0.66  |   0.75   |
|  SVM  | Custardcake |   0.875   |  0.77  |  0.823   |
|  GBM  | Custardcake |   0.875   |  0.77  |  0.823   |
+-------+-------------+-----------+--------+----------+

### fruit cake

In [163]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\fruitcake\\mixedfruit')

In [164]:
fm1 = pd.read_csv('s1.csv')
fm2 = pd.read_csv('s2.csv')
fm3 = pd.read_csv('s3.csv')
fm4 = pd.read_csv('s4.csv')

In [165]:
data6 = pd.concat([fm1,fm2,fm3,fm4],axis=0)

In [166]:
data6 = data6.loc[data6.nwords > 2, :]
data6 = data6.loc[data6.nnumbers <= 3, :]
data6 = data6.loc[data6.nwords <= 10, :]
data6 = data6.drop(["Sentence"],axis=1)
X_test = data6.drop("label",axis=1)
y_test = data6.label


In [167]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1051    1]
 [   7   36]]
Prescision :  0.972972972972973
Recall :  0.8372093023255814
F1 score :  0.9


In [168]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1051    1]
 [   6   37]]
Prescision :  0.9736842105263158
Recall :  0.8604651162790697
F1 score :  0.9135802469135803


In [169]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1050    2]
 [   6   37]]
Prescision :  0.9487179487179487
Recall :  0.8604651162790697
F1 score :  0.9024390243902439


In [170]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1050    2]
 [   6   37]]
Prescision :  0.9487179487179487
Recall :  0.8604651162790697
F1 score :  0.9024390243902439


In [171]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1050    2]
 [   6   37]]
Prescision :  0.9487179487179487
Recall :  0.8604651162790697
F1 score :  0.9024390243902439


In [ ]:
Prescision :  0.972972972972973
Recall :  0.8372093023255814
F1 score :  0.9
    
Prescision :  0.9736842105263158
Recall :  0.8604651162790697
F1 score :  0.9135802469135803
    
Prescision :  0.9487179487179487
Recall :  0.8604651162790697
F1 score :  0.9024390243902439
    
Prescision :  0.9487179487179487
Recall :  0.8604651162790697
F1 score :  0.9024390243902439

In [176]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT","Fruitcake", "0.97" , "0.837" , "0.90"])
myTable.add_row(["RF","Fruitcake", "0.97","0.860", "0.91"])
myTable.add_row(["Ada","Fruitcake",  "0.94"," 0.860", " 0.90"])
myTable.add_row(["SVM","Fruitcake", "0.94"," 0.860", "0.90"])
myTable.add_row(["GBM","Fruitcake","0.94","0.960", "0.90"])

In [177]:
myTable

+-------+-----------+-----------+--------+----------+
| Model | Site_Name | Precision | Recall | F1_score |
+-------+-----------+-----------+--------+----------+
|   DT  | Fruitcake |    0.97   | 0.837  |   0.90   |
|   RF  | Fruitcake |    0.97   | 0.860  |   0.91   |
|  Ada  | Fruitcake |    0.94   |  0.860 |   0.90   |
|  SVM  | Fruitcake |    0.94   |  0.860 |   0.90   |
|  GBM  | Fruitcake |    0.94   | 0.960  |   0.90   |
+-------+-----------+-----------+--------+----------+

### moussecake

In [179]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\moussecake\\ferrero rocher')

In [180]:
mf1 = pd.read_csv('s1.csv')
mf3 = pd.read_csv('s3.csv')
mf4 = pd.read_csv('s4.csv')

In [181]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\moussecake\\orange')

In [182]:
or1 = pd.read_csv('s1.csv')
or2 = pd.read_csv('s2.csv')
or3 = pd.read_csv('s3.csv')
or4 = pd.read_csv('s4.csv')

In [183]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\moussecake\\yogurt')

In [184]:
yo1 = pd.read_csv('s1.csv')
yo2 = pd.read_csv('s2.csv')
yo3 = pd.read_csv('s3.csv')
yo4 = pd.read_csv('s4.csv')

In [188]:
data7 = pd.concat([mf1,mf3,mf4,or1,or2,or3,or4,yo1,yo2,yo3,yo4],axis=0)

In [189]:
data7 = data7.loc[data7.nwords > 2, :]
data7 = data7.loc[data7.nnumbers <= 3, :]
data7 = data7.loc[data7.nwords <= 10, :]
data7 = data7.drop(["Sentence"],axis=1)
X_test = data7.drop("label",axis=1)
y_test = data7.label


In [190]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1503   17]
 [  47   38]]
Prescision :  0.6909090909090909
Recall :  0.4470588235294118
F1 score :  0.5428571428571429


In [191]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1509   11]
 [  58   27]]
Prescision :  0.7105263157894737
Recall :  0.3176470588235294
F1 score :  0.43902439024390244


In [192]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1511    9]
 [  63   22]]
Prescision :  0.7096774193548387
Recall :  0.25882352941176473
F1 score :  0.37931034482758624


In [193]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1510   10]
 [  60   25]]
Prescision :  0.7142857142857143
Recall :  0.29411764705882354
F1 score :  0.4166666666666667


In [194]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1511    9]
 [  60   25]]
Prescision :  0.7352941176470589
Recall :  0.29411764705882354
F1 score :  0.4201680672268907


### Pastry

In [195]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\almonddelight')

In [196]:
r1 = pd.read_csv('s1.csv')
r2 = pd.read_csv('s2.csv')
r3 = pd.read_csv('s3.csv')
r4 = pd.read_csv('s4.csv')

In [197]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\deathbychocolate')

In [198]:
rr1 = pd.read_csv('s1.csv')
rr2 = pd.read_csv('s2.csv')
rr3 = pd.read_csv('s3.csv')
rr4 = pd.read_csv('s4.csv')

In [199]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\rainbow')

In [200]:
rrr1 = pd.read_csv('s1.csv')
rrr2 = pd.read_csv('s2.csv')
rrr3 = pd.read_csv('s3.csv')


In [202]:
os.chdir('C:\\Users\\Priyanka G\\CAPSTONE_PROJECT_WORK(2022)\\cake\\pastry\\rasmalai')

In [203]:

ras2 = pd.read_csv('s2.csv')
ras3 = pd.read_csv('s3.csv')
ras4 = pd.read_csv('s4.csv')

In [206]:
data8 = pd.concat([r1,r2,r3,r4,rr1,rr2,rr3,rr4,rrr1,rrr2,rrr3,ras2,ras3,ras4],axis=0)

In [207]:
data8 = data8.loc[data8.nwords > 2, :]
data8 = data8.loc[data8.nnumbers <= 3, :]
data8 = data8.loc[data8.nwords <= 10, :]
data8 = data8.drop(["Sentence"],axis=1)
X_test = data8.drop("label",axis=1)
y_test = data8.label


In [208]:
pred = model_DT.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1899   32]
 [  35  109]]
Prescision :  0.7730496453900709
Recall :  0.7569444444444444
F1 score :  0.7649122807017544


In [209]:
pred = randomForest.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1918   13]
 [  32  112]]
Prescision :  0.896
Recall :  0.7777777777777778
F1 score :  0.8327137546468402


In [210]:
pred = clf_AD.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1918   13]
 [  34  110]]
Prescision :  0.8943089430894309
Recall :  0.7638888888888888
F1 score :  0.8239700374531834


In [211]:
pred = clf_SVM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1921   10]
 [  33  111]]
Prescision :  0.9173553719008265
Recall :  0.7708333333333334
F1 score :  0.8377358490566039


In [212]:
pred = clf_GBM.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

# Finding precision and recall
from sklearn.metrics import precision_score, recall_score
#precision_score(y_test, pred)
print("Prescision : " , precision_score(y_test, pred))
print("Recall : " , recall_score(y_test, pred))

# To compute the F1 score, simply call the f1_score() function:
from sklearn.metrics import f1_score
print("F1 score : " ,f1_score(y_test, pred))

[[1922    9]
 [  32  112]]
Prescision :  0.9256198347107438
Recall :  0.7777777777777778
F1 score :  0.8452830188679246


In [213]:
from prettytable import PrettyTable
 
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Model","Site_Name", "Precision", "Recall", "F1_score"])


myTable.add_row(["DT","Pastry", "0.77" , "0.75" , "0.76"])
myTable.add_row(["RF","Pastry", "0.89","0.77", "0.83"])
myTable.add_row(["Ada","Pastry",  "0.89"," 0.76", " 0.82"])
myTable.add_row(["SVM","Pastry", "0.91"," 0.77", "0.83"])
myTable.add_row(["GBM","Pastry","0.92","0.77", "0.84"])

In [214]:
myTable

+-------+-----------+-----------+--------+----------+
| Model | Site_Name | Precision | Recall | F1_score |
+-------+-----------+-----------+--------+----------+
|   DT  |   Pastry  |    0.77   |  0.75  |   0.76   |
|   RF  |   Pastry  |    0.89   |  0.77  |   0.83   |
|  Ada  |   Pastry  |    0.89   |  0.76  |   0.82   |
|  SVM  |   Pastry  |    0.91   |  0.77  |   0.83   |
|  GBM  |   Pastry  |    0.92   |  0.77  |   0.84   |
+-------+-----------+-----------+--------+----------+